import { Header } from "@/components/features/header/style/Header";
import { DefaultProvider } from "@/components/providers/default-provider";
import { Logo } from "@/components/ui/icons";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To do list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/icon?<generated>" type="image/png" sizes="32x32" />

      <DefaultProvider>
        <body>
           <Header>
              <Logo/>
            </Header>
          {children}
        </body>
      </DefaultProvider>
    </html>
  );
}
